### ISSUE TITLE
Newer Turris OS breaks ath10k coloring

### ISSUE THREAD

**Issue by lbeltrame** [ddrown/omnia-led-colors#2]
Probably the statistics path has changed or removed.

I found something in `/sys/bus/pci/drivers/ath10k_pci/0000\:02\:00.0/ieee80211/phy0/device/net/wlan0/statistics/` but I'm not sure it contains the data needed by this program.

**Comment by ddrown** [comment]
Unfortunately, the new driver in the latest Turris Omnia images do not export the needed stats for the ath10k. :(

**Comment by lbeltrame** [comment]
Perhaps it might be worth opening an issue on the Turris tracker and link it here so that anyone who lands, will know where to look.

**Comment by scottjl** [comment]
What's the safest way to uninstall this? Thanks

**Comment by ddrown** [comment]
you can uninstall it by running:

/etc/init.d/omnia-led-colors disable ; /etc/init.d/omnia-led-colors stop
rm /usr/sbin/omnia-led-colors /etc/init.d/omnia-led-colors

**Comment by ddrown** [comment]
The latest OS update works with 5ghz again.
