### ISSUE TITLE
Change LED Color command

### ISSUE THREAD

**Issue by veso266** [ddrown/omnia-led-colors#3]
Hi can you tell me which command must I execute in telnet shell to change LED Color from green into blue for instance?

Thanks for Anwsering and Best Regards

**Comment by ddrown** [comment]
The relevant code looks like this:

    function write_led(ledname, r, g, b)
      local fd = io.open("/sys/class/leds/omnia-led\:"..ledname.."/color", "w")
      fd:write(r .. " " .. g .. " " .. b)
      fd:close()
    end

in other words, write the values "Red Green Blue" to the file /sys/class/leds/omnia-led:LEDNAME/color

**Comment by veso266** [comment]
Thanks but I have a difrent router that also has RGB LEDs inside and has Broadcom4350 V8.0 and all the normal commands like wl and wget and all other stuff

How did you discover that your router has leds config in /sys/class ?

**Comment by ddrown** [comment]
/sys/class/leds/ should have them if they're controlled by the kernel.
