### ISSUE TITLE
Only seeing green blinking LEDs no change in color

### ISSUE THREAD

**Issue by exside** [ddrown/omnia-led-colors#5]
As title says, somehow the base color is set, but it's not changing with the bandwidth usage to another color, I tried both, your original version and the one from PR #4 (see my comment in this PR as well). Any ideas what could be the issue or is this just not working anymore?

I'm using 
`:: TurrisOS 3.8.6 :: OpenWrt omnia 15.05 :: Chaos Calmer.r47055 ::`

thanks for your work and any help with this, love this customization =)!

EDIT: Figured it out partially...the limit set by default was 10x to high for my line =)...removed a zero and now it works, but only for download, probably need to add some more configuration for upload??

**Comment by ddrown** [comment]
The file https://github.com/ddrown/omnia-led-colors/blob/master/omnia-led-colors.config shows an example config for 300Mbit down and 20Mbit up.  You can adjust those numbers in the "option limit" config.
